### ISSUE TITLE
It's owesome and easy to use. Is it possible to make it  slide automatically?

### ISSUE THREAD

**Issue by yaoyonstudio** [PaulBGD/react-native-image-slider#1]

**Comment by PaulBGD** [comment]
Yeah definitely, I'll see what I can do when I have some time.

**Comment by anton6** [comment]
Auto slide animation would definitely be a nice touch. 

Can you also please add the github link for this module to the npm (react-native-image-slider) page so more visitor can be redirected to gihub (react-native-image-slider)?

**Comment by PaulBGD** [comment]
That's strange, it should be on the sidebar of the NPM site. I'll make sure to get it on there next release.

**Comment by PaulBGD** [comment]
I didn't add this to the core code, however it's now possible to do this yourself. I added a simple example to the README.
