### ISSUE TITLE
Usage in a Modal?

### ISSUE THREAD

**Issue by mjsisley** [PaulBGD/react-native-image-slider#10]
This is a great package. Thanks!

I'm trying to use it within a Modal component (standard react-native) and swiping isn't working for me.  It seems #8 may solve this issue, as a scrollview does work within the Modal.

Have you used it in this case? If not, what is the status of #8? I may take a shot at it, but if you have made any headway... it would be great to know before starting.

**Comment by PaulBGD** [comment]
I'm working on #8 but progress is a little slow.

**Comment by PaulBGD** [comment]
Okay, let me know if this is now fixed.

**Comment by mjsisley** [comment]
This behaves the same, so seemingly #8 was not the issue. 

The image-slider doesn't respond to touch.
Here is example code (placing your example in the example for (RN modals)[https://facebook.github.io/react-native/docs/modal.html].

Please let me know if you have any ideas. Thanks!

```
constructor(props) {
    super(props);
    this.setModalVisible = this.setModalVisible.bind(this);
    this.state = {modalVisible: false};
  }  

  setModalVisible(visible) {
    this.setState({modalVisible: visible});
    }


render() {return(<CenteredContainer>
      <Modal
          animationType={"slide"}
          transparent={false}
          visible={this.state.modalVisible}
          onRequestClose={() => {alert("Modal has been closed.")}}
          >
            <View>
            <ImageSlider images={[
                'http://placeimg.com/640/480/any',
                'http://placeimg.com/640/480/any',
                'http://placeimg.com/640/480/any'
            ]}/>
            <TouchableHighlight onPress={() => {
              this.setModalVisible(!this.state.modalVisible)
            }}>
              <Text>Hide Modal</Text>
            </TouchableHighlight>

          </View>
        </Modal>

        <TouchableHighlight onPress={() => {
          this.setModalVisible(true)
        }}>
          <Text>Show Modal</Text>
        </TouchableHighlight>
      </CenteredContainer>)}
```

**Comment by PaulBGD** [comment]
I'm using your code and it works fine on iOS 9.3 and React Native 0.33. What are you running it on?

**Comment by mjsisley** [comment]
I was running on a simulator with iOS 10 and RN 0.33... but running on device, it is working.

The slider scrolls, instead of snapping, within the Modal. It works better than before outside of the Modal.

**Comment by mjsisley** [comment]
So I am seeing the same behavior as #13 describes in iOS, but only when used within a modal.

**Comment by PaulBGD** [comment]
Oh it doesn't snap? I thought you meant it wasn't scrolling.
Can you add a console.log in the `release` lambda and let me know if it's called?

**Comment by PaulBGD** [comment]
Closing due to no response.
