### ISSUE TITLE
Images are always black any idea why ? 

### ISSUE THREAD

**Issue by Aloushiz** [PaulBGD/react-native-image-slider#11]
I included the slider just like provided , everything is working except the images don't show.

**Comment by Aloushiz** [comment]
okay Correction they are not black ! they aren't even displaying any help ?

**Comment by Aloushiz** [comment]
Use HTTPS links only

**Comment by PaulBGD** [comment]
@Aloushiz That's not a limit of mine, that's because of the iOS policy.
