### ISSUE TITLE
Orientation change (android)

### ISSUE THREAD

**Issue by stefanocapitanio** [PaulBGD/react-native-image-slider#12]
When in my app I change orientation, ImageSlider doesn't "re-layout". I have to do something or it's an issue?

**Comment by PaulBGD** [comment]
This is definitely an issue on both Android and iOS, thanks for opening it!

**Comment by PaulBGD** [comment]
I did a bit of research and it looks like this is partially our issue and partially React Native's. (https://github.com/facebook/react-native/issues/25#issuecomment-122997574)
I'll see if I can get it fixed from our side.

**Comment by PaulBGD** [comment]
Let me know if this is fixed.

**Comment by stefanocapitanio** [comment]
It's still not working for me.
Maybe it's correct to put in my app a listener to undestand when width change to update your component?

**Comment by PaulBGD** [comment]
If your component that contains an image slider (or any parent) has a `shouldComponentUpdate` statement, it should return true when the width changes.

**Comment by PaulBGD** [comment]
Closing due to no response.
