### ISSUE TITLE
Use onPositionChanged Crash : Map

### ISSUE THREAD

**Issue by sundou** [PaulBGD/react-native-image-slider#14]
When i use 'onPositionChanged' like demo, the code will crash.
But if i do't use it, everything is ok.

The error message is :
![97bb44e2-75db-486b-9a6d-f819533c14f9](https://cloud.githubusercontent.com/assets/10528803/18944117/295dc59e-8656-11e6-8b33-b2037d510f0c.png)

**Comment by PaulBGD** [comment]
The error is pretty obvious. The images props you're passing is undefined. Do you have any sample code.

**Comment by sundou** [comment]
var Dimensions = require('Dimensions');
var screenHeight = Dimensions.get('window').height;

var ReviewImage = React.createClass({

    getInitialState(){
        return{
            position: 0,
        }
    },


    render() {
        return (     
            <View style={styles.container}>
                <TouchableOpacity onPress={()=>{
                                this.props.navigator.pop();
                            }}>   
                    <Text style={{color:'white', fontSize:20,marginLeft:10,marginBottom:10}}>返回</Text>
                </TouchableOpacity>

                <ImageSlider 
                // position={0}
                onPositionChanged={()=>{}}/>

                height={screenHeight*0.8}
                images={
                    // this.props.images
                    [
                        'http://placeimg.com/640/480/any',
                        'http://placeimg.com/640/480/any',
                        'http://placeimg.com/640/480/any',
                    ]
                }/>
            </View>
        );
    },

});

**Comment by PaulBGD** [comment]
I'll look into it soon, that shouldn't be happening.

**Comment by PaulBGD** [comment]
I can't reproduce. Is this error still occurring?
