### ISSUE TITLE
Add resizeMode and other options

### ISSUE THREAD

**Issue by lakhman** [PaulBGD/react-native-image-slider#15]
Could we pass other image attributes through to the image, things like `resizeMode`.

https://facebook.github.io/react-native/docs/image.html

```
<ImageSlider
    images={this.state.imageMap}
    position={this.state.imagePosition}
    onPositionChanged={(imagePosition) => this.imagePositionChanged(imagePosition)}
    height={150}
    resizeMode="contain" // ! <--- Like this
/>
```

something like this? - Is there a better way to pass only the props we need, I tried spreading all the props, but this causes issues.

This works here:

https://github.com/PaulBGD/react-native-image-slider/blob/master/ImageSlider.js#L150

```
resizeMode={this.props.resizeMode}
```

**Comment by PaulBGD** [comment]
That's a good idea, I'll get it in the next release.

**Comment by AbeHerbert** [comment]
Any update on this ticket?

**Comment by cykeltur** [comment]
@AbeHerbert so if i have a simple "working" image slider and want to try this, :+1: 
can you please explain the changes? (exept change the react-native-image-slider.JS file and install the "fit-image") ? 

example:
```
<ImageSlider
                    images={[
                      'http://111.png',
                      'http://222.png',
                      'http://333.png' 
                    ]}
                    position={this.state.position}
                    onPositionChanged={position => this.setState({ position })}
                    resizeMode="contain"
         />
```

**Comment by stokesbga** [comment]
@AbeHerbert My width is getting messed up a bit. Looks like the displacement distance is the same as the width of the device ```(Dimensions.get('device'))``` whether or not there is a width prop. Also, still have to add the resizeMode prop manually.

@cykeltur Go into Abe's ImageSlider and add ```resizeMode={this.props.resizeMode}``` to the FitImage component and then in your app component, add ```resizeMode={`whatever`} ```
RN Fit Image uses strings for that prop rather than Image.resizeMode constants, so maybe look at their documentation.

**Comment by ArtiomShapovalov** [comment]
In the last update I add support of custom slides, so you basically can customize your image any way you want. I believe this fixes the issue. Closing it for now.
