### ISSUE TITLE
npm ERR! peerinvalid The package react-native@0.21.0 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by karthickvkumar** [PaulBGD/react-native-image-slider#2]
when i try to install ur component in react-native 0.21 it showing this error...please provide me a solution asap
![selection_004](https://cloud.githubusercontent.com/assets/11032434/13485456/f2949dda-e12d-11e5-9218-02c57bba3978.png)

**Comment by PaulBGD** [comment]
Hi, I will check this out when I have free time (which might not be until next Monday).

**Comment by karthickvkumar** [comment]
@PaulBGD Did you get a chance to check this issue?

Thanks in Advance

**Comment by tigerraj32** [comment]
Using react native old version is not an option. This will spoil whole project.

**Comment by PaulBGD** [comment]
Hii @tigerraj32 I've fixed the issue in the latest commit. Thanks for the warning.
