### ISSUE TITLE
Slider swipes like one long image on Android

### ISSUE THREAD

**Issue by Clcll** [PaulBGD/react-native-image-slider#20]
How can I  swipe images like in slider not as a one ling picture. Thank you

**Comment by PaulBGD** [comment]
You'll need to be more specific, maybe give an example.

**Comment by indesignlatam** [comment]
I have found this issue to sometimes in Android only. If you scroll to next image images dont snap, they just scroll as a standard ScrollView.

I havent been able to track down where or why this happens. On android 4.4.4 happens sometimes while on android 5 or 5.1 happens always in my case.

Still i think is a styling problem as i have found other components using sliders having this very same issue.

**Comment by sundou** [comment]
@indesignlatam @PaulBGD 
I think the result he want just like ' pagingEnabled={true} ' on <ScrollView/>
On iOS everything is ok. But on Android , i have found same issue. I am Android 5.1.1 Nexus 5.
And i found the problem is Function 'onPanResponderRelease' didn't response.
If i put the 'PanResponder' on the normal <View/> , the  Function 'onPanResponderRelease' can be callback. But on <ScrollView/> can't.
It is so weird.

**Comment by indesignlatam** [comment]
The issue might be related to this facebook/react-native#9447

This could help, i havent tested it yet.

> Hello, on Android, onPanResponderTerminate will be called rather than onPanResponderRelease

**Comment by dhimoet** [comment]
Any real solution for this? Any fix on the updates?

**Comment by PaulBGD** [comment]
@dhimoet The real solution is that I need to find some time to work on this library.

**Comment by JayricMok** [comment]
I having the same issue , still can't find any solution for this. Any idea ?

**Comment by Clcll** [comment]
@JayricMok Hi, use this one https://github.com/leecade/react-native-swiper, it works perfectly for me

**Comment by JayricMok** [comment]
@Clcll Hi, thanks for your reply. I found that library also, but it feel like only for ios am i right ?

**Comment by Clcll** [comment]
@JayricMok No, it works for both platform

**Comment by JayricMok** [comment]
@Clcll oh really ? I will try it out ! Thanks you !

**Comment by Clcll** [comment]
@JayricMok Ypu're welcome
