### ISSUE TITLE
Unable to resolve module react-native-image-slider

### ISSUE THREAD

**Issue by SelfnessAid** [PaulBGD/react-native-image-slider#25]
First of all, Thanks for great package
I've tried to use this in my project. But got "Unable to resolve module react-native-image-slider" error.

Now I am using react-native@0.36.0 and react-native-image-slider@1.1.5
Very glad for any help

**Comment by PaulBGD** [comment]
Unless there's a larger error, this is an issue with NPM/react-native bundler and not an issue with this package.
