### ISSUE TITLE
onPositionChanged never fired

### ISSUE THREAD

**Issue by aloulouamine** [PaulBGD/react-native-image-slider#33]
Hi,

I'm trygin to use onPositionChanged callback but it's never fired.

I tryed your example only intervals are updating position.

Regards.

**Comment by Angelk90** [comment]
Hi, have you been able to use onPositionChanged?

**Comment by aloulouamine** [comment]
@Angelk90 No I moved on, I'm using react-native-looped-carousel instead. It have a more consistent API.
