### ISSUE TITLE
PanResponder does not work

### ISSUE THREAD

**Issue by Angelk90** [PaulBGD/react-native-image-slider#36]
Oddly PanResponder, I tried to put it in

  Let release = (e, gestureState) => {
             Const width = this.state.width;
             Const relativeDistance = gestureState.dx / width;
             Const vx = gestureState.vx;
             Let change = 0;
             console.log ("change");
             If (relativeDistance <-0.5 || (relativeDistance <0 && vx <= 0.5)) {
                 Change = 1;
             } Else if (relativeDistance> 0.5 || (relativeDistance> 0 && vx> = 0.5)) {
                 Change = -1;
             }
             Const position = this._getPosition ();
             If (position === 0 && change === -1) {
                 Change = 0;
             } Else if (position + change> = this.props.images.length) {
                 Change = (this.props.images.length) - (position + change);
             }
            
             This._move (position + change);
             Return true;
         };

A console.log but never called.

**Comment by AleksandrChernyavenko** [comment]
The same problem for me - `release` function doesn't call on android ( on ios works great )

**Comment by dodgertodd** [comment]
I removed PanResponder altogether, as demonstrated in PR #50 .

**Comment by Angelk90** [comment]
@AleksandrChernyavenko , @dodgertodd : I've seen the changes, can you request @PaulBGD  to merge the module?

**Comment by dodgertodd** [comment]
I think Paul is looking for a new maintainer, and also seems pretty intent on maintaining backwards compatibility. So I don’t expect a merge soon. But this component is really quite simple—if my version worked for you, just copy and paste from my fork!

**Comment by PaulBGD** [comment]
Sorry, I just can't spend the time to maintain this project and I don't even have a Mac anymore. If someone is interested in maintaining this, contact me!
