### ISSUE TITLE
Cannot show image

### ISSUE THREAD

**Issue by weidongdiao** [PaulBGD/react-native-image-slider#38]
When I try demo "SliderTests" in my ios react native project, the slider shows no image. 
![ee6c8efc-ae74-432c-97c4-db69aba99807](https://user-images.githubusercontent.com/12673847/27843929-35f3e104-60e8-11e7-89fc-171f6ad7b357.png)

**Comment by shikya** [comment]
Try replacing http:// with https://

**Comment by Chemik27** [comment]
Add require.

Example:  <ImageSlider images={[ **require(**' URL IMAGE '**)**}]

:)
