### ISSUE TITLE
Cannot install react-native-image-slider because of peer dependency.

### ISSUE THREAD

**Issue by tigerraj32** [PaulBGD/react-native-image-slider#4]
I have following detail 
react-native-cli: 1.0.0
react-native: 0.26.3
node: v4.4.3

Now when i try to install the package with following command.
`npm install react-native-image-slider@latest --save`

The peer dependency react-native@^0.14.1 included from react-native-image-slider will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

**Comment by PaulBGD** [comment]
As it says, it's a warning not an error.

**Comment by tigerraj32** [comment]
Yes it's warning, but because of that  the package cannot be installed.  I think I did not provide  sufficient information

npm install react-native-image-slider@latest --save
npm WARN peerDependencies The peer dependency react-native@^0.14.1 included from react-native-image-slider will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-native-image-slider@latest" "--save"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native@0.26.3 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-action-button@1.1.5 wants react-native@>=0.11
npm ERR! peerinvalid Peer react-native-grid-view@0.4.1 wants react-native@>=0.25.1
npm ERR! peerinvalid Peer react-native-scrollable-tab-view@0.4.4 wants react-native@>=0.20.0
npm ERR! peerinvalid Peer react-native-simple-modal@3.0.4 wants react-native@>=0.17.0
npm ERR! peerinvalid Peer react-native-image-slider@1.0.2 wants react-native@^0.14.1

**Comment by PaulBGD** [comment]
I'll look into it, more than likely I just need to specify react-native as a wildcard.

**Comment by PaulBGD** [comment]
Sorry for the long wait, it's a wildcard now. Let me know if you still get the error.

**Comment by TiagoPereiraOPT** [comment]
I still have the same problem.
