### ISSUE TITLE
ImageSlider height is 15px less than the image inside

### ISSUE THREAD

**Issue by kdong007** [PaulBGD/react-native-image-slider#40]
![2017-08-08 12 42 46](https://user-images.githubusercontent.com/26269173/29106931-8828d866-7c8c-11e7-989d-f8c86c6fa667.png)
![2017-08-08 12 42 49](https://user-images.githubusercontent.com/26269173/29106932-8840cd90-7c8c-11e7-9709-4aa245970c83.png)

Here is the code I used.
`return (<View style={styles.container}>
            <ImageSlider images={[
                require('./../res/apt1.jpg'),
                require('./../res/apt2.jpg'),
                require('./../res/apt3.jpg'),
                require('./../res/apt4.jpg'),
                require('./../res/apt5.jpg'),
            ]}/>
            <View>
            <Text>Community</Text>
            </View>
        </View>);`

**Comment by PaulBGD** [comment]
The simple fix is passing `height` set to the height of the largest image.
The longer fix is this library needs some love and care so that it works better.

**Comment by pcooney10** [comment]
hey @kdong007 - what tool are you using to inspect / debug your application ? Thanks

**Comment by PaulBGD** [comment]
@pcooney10 That is the built-in inspect tool that React native has. Open the developer menu to access it.

**Comment by dodgertodd** [comment]
I found that changing `flex` to `flexbox` fixed this for me.

**Comment by ArtiomShapovalov** [comment]
There should be no such issue in a new version of the module. Please, could you try to use it again? Let me know if it stays as an issue. I'm closing this for now.
