### ISSUE TITLE
Deleting image from array after sliding is showing blank screen

### ISSUE THREAD

**Issue by shridharmalagi** [PaulBGD/react-native-image-slider#42]
I am working with react-native-image-slider .Slider is working perfect with array of images.I want to delete particular image while sliding at particular index.Suppose after sliding multiple images ,I am at index 6 and now i want to delete that image which is available at index 6.When i am using javascript splice method to delete and setting state with updated array after delete ,I am not able to see anything in slider.Can anyone help me out here.

**Comment by PaulBGD** [comment]
Splice isn't a very good method because it mutates the original array. Try using slice instead.

**Comment by shridharmalagi** [comment]
Why after setting state with new Array only updating view but not updating onPositionChanged prop?

**Comment by shridharmalagi** [comment]
See I am deleting image like this:-

  _deleteImageFromSlider(index){
      
       
        var newArray = update(this.state.imageFlatlist, {$splice: [[index, 1]]});
        this.setState({
            imageFlatlist:newArray
          })
        
    }
    

    _deleteImage(array ,index) {
      
        return array.slice(0,index).concat(array.slice(index+1))
       
        }

**Comment by shridharmalagi** [comment]
<ImageSlider images={this.state.imageFlatlist}
                                            onPositionChanged={position => this._currentImagePosition(position)}
                                            style={{ flex: 1, }}

**Comment by shridharmalagi** [comment]
Anything else i need to do?

**Comment by shridharmalagi** [comment]
Please go through this: 
https://stackoverflow.com/questions/46405716/deleting-image-from-slider-doesnt-show-anything/46413707?noredirect=1#comment79816360_46413707

**Comment by shridharmalagi** [comment]
@PaulBGD  please suggest me what to do .

**Comment by shridharmalagi** [comment]
I solved this issue ..
