### ISSUE TITLE
Add an example for onPress ?

### ISSUE THREAD

**Issue by hegemon33** [PaulBGD/react-native-image-slider#44]
Hello, 
Thanks a lot for providing such great package.
Can you add an example to teach users how to use onPress?

Thanks a lot.

**Comment by pcooney10** [comment]
Hey @hegemon33, you might want to do something like this:

```js
<ImageSlider
  ...
  onPress={(x) => this.props.handlePress(x)}
  ...
/>
```
Where x will be an object that looks like this:
```json
{ "image": "https://...", "index": 0 }
```

**Comment by ksetrin** [comment]
<ImageSlider
              loop={false}
              loopBothSides={false}
              images={this.props.availableImages}
              onPress={({ index }) => console.log(index)}
              ...

onPress doesn't work here. How to handle it?

**Comment by AbdurRehman26** [comment]
Anyone who knows this answer ? having this same issue with customSlides

**Comment by fmchan** [comment]
```
  handleSlides = ({image, index}) => {
    console.log(index);
  };
```

Slideshow:
`<Slideshow dataSource={slides} onPress={this.handleSlides} />`

Cheers
