### ISSUE TITLE
I am unable to maintain this project

### ISSUE THREAD

**Issue by PaulBGD** [PaulBGD/react-native-image-slider#45]
Due to a change in the type of work I'm doing, I don't have the time or even a mac to be able to maintain this project. If anyone is interested in maintaining it, please reply to this issue or send an email to paul@burngames.net.

**Comment by ArtiomShapovalov** [comment]
Hey! 👋 
What did happen and can I help you? I am interested in maintaining this module, I use it in my current project. I have tuned it to my needs a little bit #53.
Cheers

**Comment by ArtiomShapovalov** [comment]
Good day, could you please tell me are you still looking for a maintainer? I have investigated all the project issues and can provide my help in future PRs.

**Comment by ArtiomShapovalov** [comment]
Hey, thank you for making me a collab!) There is only one thing left to do. I need your permission to an npm package, I can not publish changes there.

**Comment by PaulBGD** [comment]
@ArtiomShapovalov Done!

If you need anything additional, just tag me or DM me on twitter (@PaulBGD)
