### ISSUE TITLE
onPositionChanged returns the old position not the new one

### ISSUE THREAD

**Issue by vranjesluka** [PaulBGD/react-native-image-slider#55]
When calling onPositionChanged the position that is returned is the old position, not the new one.

For example, when i got from 2->1 I get the postion 2, also when I got from 2->3 i get the positon 2.

### Environment

react-native-image-slider version: 2.0.1
React Native version: 0.53
Platform: Android and iOS

**Comment by ArtiomShapovalov** [comment]
Thank you for the report! I'll check it out soon

**Comment by vranjesluka** [comment]
```
_handleScroll = (event: Object) => {
    const { position, width } = this.state;
    const { loop, loopBothSides, images, onPositionChanged } = this.props;
    const { x } = event.nativeEvent.contentOffset;

    if (
        (loop || loopBothSides) &&
        x.toFixed() >= +(width * images.length).toFixed()
    ) {
        return this._move(0, false);
    } else if (loopBothSides && x.toFixed() <= +(-width).toFixed()) {
        return this._move(images.length - 1, false);
    }

    const newPosition = Math.round(event.nativeEvent.contentOffset.x / width);
    if (position !== -1 && position !== images.length) {
        this.setState({
            position: newPosition,
        });
    }

    if (onPositionChanged && !this.state.onPositionChangedCalled) {
        onPositionChanged(newPosition);
    } else {
        this.setState({ onPositionChangedCalled: false });
    }

    this._setInterval();
};
```

This solves my problem, but I don't have a loop turned on so I'm not sure if this brakes any other case.

But the problem is probably that the setState is Asynchronous and doesn't change the state right away. And you are using position from state that is not yet changed.

**Comment by ArtiomShapovalov** [comment]
Just push changes, I believe that should fix it. Could you try a new version, please?

**Comment by vranjesluka** [comment]
It works great! 
Thank you very much for the prompt response and fix.
