### ISSUE TITLE
Setting height to the image slider

### ISSUE THREAD

**Issue by vranjesluka** [PaulBGD/react-native-image-slider#56]
I am trying to set a height to the slider. 

I tried to figure out what exactly is the cause of the problem, but I can't help.
I have tried multiple ways.

Example of the code:
```
<ImageSlider
    style={{width: 360, height: 270}}
    images={images}
/>
```
![simulator screen shot - iphone 8 - 2018-02-10 at 18 36 17](https://user-images.githubusercontent.com/8490079/36064821-64fa7128-0e91-11e8-9f87-8bfeea24183d.png)

I have also tryed:
```
<ImageSlider
    images={images}
    customSlide={({ index, item, style, width }) => (
        <Image source={{ uri: item }} style={{width: 360, height: 270}} />
    )}
/>
```
![simulator screen shot - iphone 8 - 2018-02-10 at 18 30 17](https://user-images.githubusercontent.com/8490079/36064825-6efb8202-0e91-11e8-80b3-f833698505df.png)

And also:
```
<ImageSlider
    style={{width: 360, height: 270}}
    images={images}
    customSlide={({ index, item, style, width }) => (
        <Image source={{ uri: item }} style={{width: 360, height: 270}} />
    )}
/>
```
![simulator screen shot - iphone 8 - 2018-02-10 at 18 35 58](https://user-images.githubusercontent.com/8490079/36064826-753ff27e-0e91-11e8-87f7-eef3845ec5cd.png)

**Comment by ArtiomShapovalov** [comment]
Hey!
Could you try to replace ```<ImageSlider style={image_slider: {width: 360, height: 270}} ...```
with ```<ImageSlider style={{width: 360, height: 270}} ...```?

**Comment by vranjesluka** [comment]
Yeah, that's how I tried, I c/p it wrong here, sorry. It was

`<ImageSlider style={{width: 360, height: 270}} ...`

**Comment by vranjesluka** [comment]
I tried it again just in case

**Comment by ArtiomShapovalov** [comment]
All right I got it. Could you try to pass ```flex: 0``` with your style prop?

**Comment by vranjesluka** [comment]
With the new update and `flex: 0` it works. Thank you!
