### ISSUE TITLE
Add default source

### ISSUE THREAD

**Issue by vranjesluka** [PaulBGD/react-native-image-slider#57]
Add default source to the images, so the images have placeholders while loading

My suggest solution `line 193`:
```
<Image key={index} defaultSource={this.props.defaultSource} source={imageObject} style={[imageStyle]} />
```

**Comment by vranjesluka** [comment]
I just realized `defaultSource` doesn't work on Android.

**Comment by ArtiomShapovalov** [comment]
Hey! In case you are still wondering how to solve your issue, the behaviour you are looking for can be achieved by implementing ```customSlide``` prop.

Something like that should work:

```
<View style={slide}>
 <Image sourse={defaultImg} style={{position: 'absolute', ...}} />
 <Image sourse={slideImg} style={img} />
</View>
```

**Comment by vranjesluka** [comment]
Thanks it worked! 👍
