### ISSUE TITLE
Changing The index 

### ISSUE THREAD

**Issue by AriaGrt** [PaulBGD/react-native-image-slider#60]
Is it possible to somehow change the index of the slider image when clicking outside of the slider?

**Comment by ArtiomShapovalov** [comment]
Hey!

That's easy 😉. Add ref to your ```ImageSlider``` component and then call this function

```
onPress={() => this.slider && this.slider._move(2)}
```
_move takes a slide index (starting from 0) and an animated value (default=true)

**Comment by AriaGrt** [comment]
I am not sure you understood me. Maybe my question was a bit blurred or i didn't understand your answer.
I want to change the index of the slider from outside of the <ImageSlider/> container
So the onPress will be outside of the <ImageSlider/> If so, what shall i put in my ref?

**Comment by ArtiomShapovalov** [comment]
Basically, what you are looking for would look something like this

```js
...
<TouchableOpacity
  onPress={() => this.slider && this.slider._move(2)}
>
 <Text>Any Component</Text>
</TouchableOpacity>

<ImageSlider ref={slider => (this.slider = slider)} ... />
...
```

**Comment by AriaGrt** [comment]
Okay i get it now thanks so much for teaching me this trick. Closing the issue and wishing you a good day my friend 😃
