### ISSUE TITLE
Image Slider Hiding Issue 

### ISSUE THREAD

**Issue by sajjidakr** [PaulBGD/react-native-image-slider#9]
I am using react-native-scrollable-tab-view where on one of the tab screen i have placed this image slider, on switching tabs the image slider still shows which it should not. I have not used any custom styling.

**Comment by PaulBGD** [comment]
Also I think #8 might fix this, since the reason it's probably showing is because of the fixed positions.

**Comment by sajjidakr** [comment]
Thanks for replying, But how i am supposed to fix this "fixed position issue" using react-native-scrollable-tab-view

**Comment by PaulBGD** [comment]
@sajjidakr Well, if I could get a minimal reproduction case so I can figure out where the issue is, I could fix it a lot faster.

**Comment by PaulBGD** [comment]
Okay, let me know if this has been fixed.

**Comment by PaulBGD** [comment]
Closing due to no response.
